on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: main
            - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
