name: 'Trigger action'
on:
  workflow_dispatch:
  

jobs:
  trigger_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script1
        run: echo "Code coverage issue for "
